export const ADD_FOOD_ORDER = "ADD_FOOD_ORDER";

export const VIEW_ORDER = "VIEW_ORDER";

export const VIEW_FOOD_ORDER = "VIEW_FOOD_ORDER";

export const FIND_ORDERS = "FIND_ORDERS";

export const DELETE_FOOD_ORDER = "DELETE_FOOD_ORDER";

export const UPDATE_FOOD_ORDER = "UPDATE_FOOD_ORDER";
