export const CREATE_RESTAURANT = "CREATE_RESTAURANT";

export const FIND_ALL_RESTAURANT = "FIND_ALL_RESTAURANT";

export const FIND_RESTAURANT = "FIND_RESTAURANT";

export const DELETE_RESTAURANT = "DELETE_RESTAURANT";

export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
