export const SEARCH_TERM_LOCAL = "SEARCH_TERM_LOCAL";

export const SEARCH_LOCATION_LOCAL = "SEARCH_LOCATION_LOCAL";

export const SEARCH_NEARBY = "SEARCH_NEARBY_YELP";

export const SEARCH_COORDINATES = "SEARCH_COORDINATES_YELP";

export const SEARCH_BUSINESS_DETAILS = "SEARCH_BUSINESS_DETAILS";

